### ISSUE TITLE
Suggested updates to HCD work

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-human-centered-design#4]
3.) Suggested rewording:

Our practice: We believe stories aren't complete until we see end-users (not experts or developers), using the piece of software developed to meet the story. We think usability testing each story helps us a) catch bugs that only exist in the user's environments, b) validate that we have met the users' need. We consider stories complete if users complete the task. We will write new stories for potential improvements when the usability testing suggests their may be an additional feature that will add additional value.

How 18F supports POs: We make sure usability testing meets a set of minimum standards. We also coach vendors on how to conduct testing, report its results to the product owner, and generate new stories from the results.

4.) I wonder if makes sense to show the hierarchy of decision making a little more clearly

Our practice: <removed the first sentence as its captured below>. a) If a design decision is controversial because of a disagreement amongst the team, or between the team and stakeholders, we conduct research to help arbitrate it. b) If research is inconclusive or impossible, we will implement the "industry best practice" or how everyone else does it. c) If there's no good research or best practice, it will be up to the product owner to decide on the design.

**Comment by colinpmacarthur** [comment]
Changes made!
